BluefruitLE_SPI_Stream Class Reference
#include <BluefruitLE_SPI_Stream.h>
Public Member Functions
BluefruitLE_SPI_Stream (int8_t csPin, int8_t irqPin, int8_t rstPin)
void setLocalName (const char *localName)
void setAdvertisingInterval (unsigned short advertisingInterval)
void setConnectionInterval (unsigned short minConnInterval, unsigned short maxConnInterval)
void setFlushInterval (int flushInterval)
void begin ()
bool poll ()
void end ()
size_t write (uint8_t byte)
int available ()
int read ()
int peek ()
void flush ()
Detailed Description
Definition at line 14 of file BluefruitLE_SPI_Stream.h.
Constructor & Destructor Documentation
BluefruitLE_SPI_Stream()
BluefruitLE_SPI_Stream::BluefruitLE_SPI_Stream (int8_t csPin, int8_t irqPin, int8_t rstPin)
Definition at line 51 of file BluefruitLE_SPI_Stream.h.
                                                                                         :
  ble(csPin, irqPin, rstPin),
  advertisingInterval(0),
  minConnInterval(0),
  maxConnInterval(0),
  txCount(0)
{ }
Member Function Documentation
available()
int BluefruitLE_SPI_Stream::available (void)
Definition at line 145 of file BluefruitLE_SPI_Stream.h.
{
  return ble.available();
}
begin()
void BluefruitLE_SPI_Stream::begin (void)
Definition at line 80 of file BluefruitLE_SPI_Stream.h.
{
  // Initialize the SPI interface
  ble.begin();
  // Perform a factory reset to make sure everything is in a known state
  ble.factoryReset();
  // Disable command echo from Bluefruit
  ble.echo(false);
  // Change the MODE LED to indicate BLE UART activity
  ble.println("AT+HWMODELED=BLEUART");
  // Set local name
  if (localName.length() > 0) {
    ble.print("AT+GAPDEVNAME=");
    ble.println(localName);
  }
  // Set connection and advertising intervals
  ble.print("AT+GAPINTERVALS=");
  if (minConnInterval > 0) ble.print(minConnInterval);
  ble.print(",");
  if (maxConnInterval > 0) ble.print(maxConnInterval);
  ble.print(",");
  if (advertisingInterval > 0) ble.print(advertisingInterval);
  ble.print(",,"); // Always omit fast advertising timeout, hence two commas
  if (advertisingInterval > 0) ble.print(advertisingInterval);
  ble.println();
  // Disable real and simulated mode switch (i.e. "+++") command
  ble.println("AT+MODESWITCHEN=local,0");
  ble.enableModeSwitchCommand(false);
  // Switch to data mode
  ble.setMode(BLUEFRUIT_MODE_DATA);
}
end()
void BluefruitLE_SPI_Stream::end (void)
Definition at line 132 of file BluefruitLE_SPI_Stream.h.
{
  flush();
  ble.end();
}
References flush().
flush()
void BluefruitLE_SPI_Stream::flush (void)
Definition at line 160 of file BluefruitLE_SPI_Stream.h.
{
  ble.write(txBuffer, txCount);
  txCount = 0;
}
Referenced by end(), poll(), and write().
peek()
int BluefruitLE_SPI_Stream::peek (void)
Definition at line 155 of file BluefruitLE_SPI_Stream.h.
{
  return ble.peek();
}
poll()
bool BluefruitLE_SPI_Stream::poll ()
Definition at line 119 of file BluefruitLE_SPI_Stream.h.
{
  // If there's outgoing data in the buffer, just send it. The firmware on
  // the nRF51822 will decide when to transmit the data in its TX FIFO.
  if (txCount) flush();
  // In order to check for a connection, we would need to switch from data to
  // command mode and back again. However, due to the internal workings of
  // Adafruit_BluefruitLE_SPI, this can lead to unread incoming data being
  // lost. Therefore, we always return true.
  return true;
}
References flush().
read()
int BluefruitLE_SPI_Stream::read (void)
Definition at line 150 of file BluefruitLE_SPI_Stream.h.
{
  return ble.read();
}
setAdvertisingInterval()
void BluefruitLE_SPI_Stream::setAdvertisingInterval (unsigned short advertisingInterval)
Definition at line 64 of file BluefruitLE_SPI_Stream.h.
{
  this->advertisingInterval = advertisingInterval;
}
setConnectionInterval()
void BluefruitLE_SPI_Stream::setConnectionInterval (unsigned short minConnInterval, unsigned short maxConnInterval)
Definition at line 69 of file BluefruitLE_SPI_Stream.h.
{
  this->minConnInterval = minConnInterval;
  this->maxConnInterval = maxConnInterval;
}
setFlushInterval()
void BluefruitLE_SPI_Stream::setFlushInterval (int flushInterval)
Definition at line 75 of file BluefruitLE_SPI_Stream.h.
{
  // Not used
}
setLocalName()
void BluefruitLE_SPI_Stream::setLocalName (const char * localName)
Definition at line 59 of file BluefruitLE_SPI_Stream.h.
{
  this->localName = localName;
}
write()
size_t BluefruitLE_SPI_Stream::write (uint8_t byte)
Definition at line 138 of file BluefruitLE_SPI_Stream.h.
{
  txBuffer[txCount++] = byte;
  if (txCount == sizeof(txBuffer)) flush();
  return 1;
}
References flush().
The documentation for this class was generated from the following file:
BluefruitLE_SPI_Stream.h