EthernetClientStream Class Reference
#include <EthernetClientStream.h>
Public Member Functions
EthernetClientStream (Client &client, IPAddress localip, IPAddress ip, const char *host, uint16_t port)
int available ()
int read ()
int peek ()
void flush ()
size_t write (uint8_t)
void maintain (IPAddress localip)
Detailed Description
Definition at line 31 of file EthernetClientStream.h.
Constructor & Destructor Documentation
EthernetClientStream()
EthernetClientStream::EthernetClientStream (Client & client, IPAddress localip, IPAddress ip, const char * host, uint16_t port)
Definition at line 60 of file EthernetClientStream.h.
  : client(client),
    localip(localip),
    ip(ip),
    host(host),
    port(port),
    connected(false)
{
}
Member Function Documentation
available()
int EthernetClientStream::available (void)
Definition at line 71 of file EthernetClientStream.h.
{
  return maintain() ? client.available() : 0;
}
References maintain().
flush()
void EthernetClientStream::flush (void)
Definition at line 88 of file EthernetClientStream.h.
{
  if (maintain())
    client.flush();
}
References maintain().
maintain()
void EthernetClientStream::maintain (IPAddress localip)
Definition at line 101 of file EthernetClientStream.h.
{
  // ensure the local IP is updated in the case that it is changed by the DHCP server
  if (this->localip != localip) {
    this->localip = localip;
    if (connected)
      stop();
  }
}
References maintain().
Referenced by available(), flush(), maintain(), peek(), read(), and write().
peek()
int EthernetClientStream::peek (void)
Definition at line 83 of file EthernetClientStream.h.
{
  return maintain() ? client.peek() : -1;
}
References maintain().
read()
int EthernetClientStream::read (void)
Definition at line 77 of file EthernetClientStream.h.
{
  return maintain() ? client.read() : -1;
}
References maintain().
write()
size_t EthernetClientStream::write (uint8_t c)
Definition at line 95 of file EthernetClientStream.h.
{
  return maintain() ? client.write(c) : 0;
}
References maintain().
The documentation for this class was generated from the following file:
EthernetClientStream.h