WiFiServerStream Class Reference
#include <WiFiServerStream.h>
Public Member Functions
WiFiServerStream (uint16_t server_port)
virtual bool maintain ()
virtual void stop ()
Protected Member Functions
virtual bool connect_client ()
Protected Attributes
WiFiServer _server = WiFiServer(3030)
bool _listening = false
Detailed Description
Definition at line 31 of file WiFiServerStream.h.
Constructor & Destructor Documentation
WiFiServerStream()
WiFiServerStream::WiFiServerStream (uint16_t server_port) [inline]
create a WiFi stream with a TCP server
Definition at line 66 of file WiFiServerStream.h.
: WiFiStream(server_port) {}
Member Function Documentation
connect_client()
virtual bool WiFiServerStream::connect_client () [inline], [protected], [virtual]
check if TCP client is connected
Returns
true if connected
Implements WiFiStream.
Definition at line 41 of file WiFiServerStream.h.
  {
    if (_connected)
    {
      if (_client && _client.connected()) return true;
      stop();
    }
    // passive TCP connect (accept)
    WiFiClient newClient = _server.available();
    if (!newClient) return false;
    _client = newClient;
    _connected = true;
    if (_currentHostConnectionCallback)
    {
      (*_currentHostConnectionCallback)(HOST_CONNECTION_CONNECTED);
    }
    return true;
  }
References WiFiStream::_client, WiFiStream::_connected, WiFiStream::_currentHostConnectionCallback, _server, HOST_CONNECTION_CONNECTED, and stop().
Referenced by maintain().
maintain()
virtual bool WiFiServerStream::maintain () [inline], [virtual]
maintain WiFi and TCP connection
Returns
true if WiFi and TCP connection are established
Implements WiFiStream.
Definition at line 72 of file WiFiServerStream.h.
  {
    if (connect_client()) return true;
    stop();
    if (!_listening && WiFi.status() == WL_CONNECTED)
    {
      // start TCP server after first WiFi connect
      _server = WiFiServer(_port);
      _server.begin();
      _listening = true;
    }
    return false;
  }
References _listening, WiFiStream::_port, _server, connect_client(), and stop().
stop()
virtual void WiFiServerStream::stop () [inline], [virtual]
stop client connection
Implements WiFiStream.
Definition at line 92 of file WiFiServerStream.h.
  {
    if (_client)
    {
      _client.stop();
      if (_currentHostConnectionCallback)
      {
        (*_currentHostConnectionCallback)(HOST_CONNECTION_DISCONNECTED);
      }
    }
    _connected = false;
  }
References WiFiStream::_client, WiFiStream::_connected, WiFiStream::_currentHostConnectionCallback, and HOST_CONNECTION_DISCONNECTED.
Referenced by connect_client(), and maintain().
Field Documentation
_listening
bool WiFiServerStream::_listening = false [protected]
Definition at line 35 of file WiFiServerStream.h.
Referenced by maintain().
_server
WiFiServer WiFiServerStream::_server = WiFiServer(3030) [protected]
Definition at line 34 of file WiFiServerStream.h.
Referenced by connect_client(), and maintain().
The documentation for this class was generated from the following file:
WiFiServerStream.h