EthernetServerStream Class Reference
#include <EthernetServerStream.h>
Public Member Functions
EthernetServerStream (IPAddress localip, uint16_t port)
int available ()
int read ()
int peek ()
void flush ()
size_t write (uint8_t)
void maintain (IPAddress localip)
Protected Member Functions
bool connect_client ()
Protected Attributes
EthernetServer server = EthernetServer(3030)
bool listening = false
Detailed Description
Definition at line 26 of file EthernetServerStream.h.
Constructor & Destructor Documentation
EthernetServerStream()
EthernetServerStream::EthernetServerStream (IPAddress localip, uint16_t port)
Definition at line 57 of file EthernetServerStream.h.
  : localip(localip),
    port(port),
    connected(false)
{
}
Member Function Documentation
available()
int EthernetServerStream::available (void)
Definition at line 81 of file EthernetServerStream.h.
{
  return maintain() ? client.available() : 0;
}
References maintain().
connect_client()
bool EthernetServerStream::connect_client () [protected]
Definition at line 64 of file EthernetServerStream.h.
  {
    if (connected)
    {
      if (client && client.connected()) return true;
      stop();
    }
    EthernetClient newClient = server.available();
    if (!newClient) return false;
    client = newClient;
    connected = true;
    DEBUG_PRINTLN("Connected");
    return true;
  }
References DEBUG_PRINTLN, and server.
flush()
void EthernetServerStream::flush (void)
Definition at line 98 of file EthernetServerStream.h.
{
  if (maintain())
    client.flush();
}
References maintain().
maintain()
void EthernetServerStream::maintain (IPAddress localip)
Definition at line 111 of file EthernetServerStream.h.
{
  // ensure the local IP is updated in the case that it is changed by the DHCP server
  if (this->localip != localip) {
    this->localip = localip;
    if (connected)
      stop();
  }
}
References maintain().
Referenced by available(), flush(), maintain(), peek(), read(), and write().
peek()
int EthernetServerStream::peek (void)
Definition at line 93 of file EthernetServerStream.h.
{
  return maintain() ? client.peek() : -1;
}
References maintain().
read()
int EthernetServerStream::read (void)
Definition at line 87 of file EthernetServerStream.h.
{
  return maintain() ? client.read() : -1;
}
References maintain().
write()
size_t EthernetServerStream::write (uint8_t c)
Definition at line 105 of file EthernetServerStream.h.
{
  return maintain() ? client.write(c) : 0;
}
References maintain().
Field Documentation
listening
bool EthernetServerStream::listening = false [protected]
Definition at line 47 of file EthernetServerStream.h.
server
EthernetServer EthernetServerStream::server = EthernetServer(3030) [protected]
Definition at line 46 of file EthernetServerStream.h.
Referenced by connect_client().
The documentation for this class was generated from the following file:
EthernetServerStream.h