firmata::FirmataParser Class Reference
#include <FirmataParser.h>
Public Types
typedef void(* callbackFunction) (void *context, uint8_t command, uint16_t value)
typedef void(* dataBufferOverflowCallbackFunction) (void *context)
typedef void(* stringCallbackFunction) (void *context, const char *c_str)
typedef void(* sysexCallbackFunction) (void *context, uint8_t command, size_t argc, uint8_t *argv)
typedef void(* systemCallbackFunction) (void *context)
typedef void(* versionCallbackFunction) (void *context, size_t sv_major, size_t sv_minor, const char *firmware)
Public Member Functions
FirmataParser (uint8_t *dataBuffer=(uint8_t *) NULL, size_t dataBufferSize=0)
void parse (uint8_t value)
bool isParsingMessage (void) const
int setDataBufferOfSize (uint8_t *dataBuffer, size_t dataBufferSize)
void attach (uint8_t command, callbackFunction newFunction, void *context=NULL)
void attach (dataBufferOverflowCallbackFunction newFunction, void *context=NULL)
void attach (uint8_t command, stringCallbackFunction newFunction, void *context=NULL)
void attach (uint8_t command, sysexCallbackFunction newFunction, void *context=NULL)
void attach (uint8_t command, systemCallbackFunction newFunction, void *context=NULL)
void attach (uint8_t command, versionCallbackFunction newFunction, void *context=NULL)
void detach (uint8_t command)
void detach (dataBufferOverflowCallbackFunction)
Detailed Description
Definition at line 27 of file FirmataParser.h.
Member Typedef Documentation
callbackFunction
typedef void(* firmata::FirmataParser::callbackFunction) (void *context, uint8_t command, uint16_t value)
Definition at line 31 of file FirmataParser.h.
dataBufferOverflowCallbackFunction
typedef void(* firmata::FirmataParser::dataBufferOverflowCallbackFunction) (void *context)
Definition at line 32 of file FirmataParser.h.
stringCallbackFunction
typedef void(* firmata::FirmataParser::stringCallbackFunction) (void *context, const char *c_str)
Definition at line 33 of file FirmataParser.h.
sysexCallbackFunction
typedef void(* firmata::FirmataParser::sysexCallbackFunction) (void *context, uint8_t command, size_t argc, uint8_t *argv)
Definition at line 34 of file FirmataParser.h.
systemCallbackFunction
typedef void(* firmata::FirmataParser::systemCallbackFunction) (void *context)
Definition at line 35 of file FirmataParser.h.
versionCallbackFunction
typedef void(* firmata::FirmataParser::versionCallbackFunction) (void *context, size_t sv_major, size_t sv_minor, const char *firmware)
Definition at line 36 of file FirmataParser.h.
Constructor & Destructor Documentation
FirmataParser()
FirmataParser::FirmataParser (uint8_t * dataBuffer = (uint8_t *)NULL, size_t dataBufferSize = 0)
The FirmataParser class.
Parameters
dataBuffer A pointer to an external buffer used to store parsed data
dataBufferSize The size of the external buffer
Definition at line 33 of file FirmataParser.cpp.
:
  dataBuffer(dataBuffer),
  dataBufferSize(dataBufferSize),
  executeMultiByteCommand(0),
  multiByteChannel(0),
  waitForData(0),
  parsingSysex(false),
  sysexBytesRead(0),
  currentAnalogCallbackContext((void *)NULL),
  currentDigitalCallbackContext((void *)NULL),
  currentReportAnalogCallbackContext((void *)NULL),
  currentReportDigitalCallbackContext((void *)NULL),
  currentPinModeCallbackContext((void *)NULL),
  currentPinValueCallbackContext((void *)NULL),
  currentReportFirmwareCallbackContext((void *)NULL),
  currentReportVersionCallbackContext((void *)NULL),
  currentDataBufferOverflowCallbackContext((void *)NULL),
  currentStringCallbackContext((void *)NULL),
  currentSysexCallbackContext((void *)NULL),
  currentSystemResetCallbackContext((void *)NULL),
  currentAnalogCallback((callbackFunction)NULL),
  currentDigitalCallback((callbackFunction)NULL),
  currentReportAnalogCallback((callbackFunction)NULL),
  currentReportDigitalCallback((callbackFunction)NULL),
  currentPinModeCallback((callbackFunction)NULL),
  currentPinValueCallback((callbackFunction)NULL),
  currentDataBufferOverflowCallback((dataBufferOverflowCallbackFunction)NULL),
  currentStringCallback((stringCallbackFunction)NULL),
  currentSysexCallback((sysexCallbackFunction)NULL),
  currentReportFirmwareCallback((versionCallbackFunction)NULL),
  currentReportVersionCallback((systemCallbackFunction)NULL),
  currentSystemResetCallback((systemCallbackFunction)NULL)
{
    allowBufferUpdate = ((uint8_t *)NULL == dataBuffer);
}
Member Function Documentation
attach() [1/6]
void FirmataParser::attach (dataBufferOverflowCallbackFunction newFunction, void * context = NULL)
Attach a buffer overflow callback
Parameters
newFunction A reference to the buffer overflow callback function to attach.
context An optional context to be provided to the callback function (NULL by default).
Note
The context parameter is provided so you can pass a parameter, by reference, to your callback function.
Definition at line 326 of file FirmataParser.cpp.
{
  currentDataBufferOverflowCallback = newFunction;
  currentDataBufferOverflowCallbackContext = context;
}
attach() [2/6]
void FirmataParser::attach (uint8_t command, callbackFunction newFunction, void * context = NULL)
Attach a generic sysex callback function to a command (options are: ANALOG_MESSAGE, DIGITAL_MESSAGE, REPORT_ANALOG, REPORT DIGITAL, SET_PIN_MODE and SET_DIGITAL_PIN_VALUE).
Parameters
command The ID of the command to attach a callback function to.
newFunction A reference to the callback function to attach.
context An optional context to be provided to the callback function (NULL by default).
Note
The context parameter is provided so you can pass a parameter, by reference, to your callback function.
Definition at line 216 of file FirmataParser.cpp.
{
  switch (command) {
    case ANALOG_MESSAGE:
      currentAnalogCallback = newFunction;
      currentAnalogCallbackContext = context;
      break;
    case DIGITAL_MESSAGE:
      currentDigitalCallback = newFunction;
      currentDigitalCallbackContext = context;
      break;
    case REPORT_ANALOG:
      currentReportAnalogCallback = newFunction;
      currentReportAnalogCallbackContext = context;
      break;
    case REPORT_DIGITAL:
      currentReportDigitalCallback = newFunction;
      currentReportDigitalCallbackContext = context;
      break;
    case SET_PIN_MODE:
      currentPinModeCallback = newFunction;
      currentPinModeCallbackContext = context;
      break;
    case SET_DIGITAL_PIN_VALUE:
      currentPinValueCallback = newFunction;
      currentPinValueCallbackContext = context;
      break;
  }
}
References firmata::ANALOG_MESSAGE, firmata::DIGITAL_MESSAGE, firmata::REPORT_ANALOG, firmata::REPORT_DIGITAL, firmata::SET_DIGITAL_PIN_VALUE, and firmata::SET_PIN_MODE.
Referenced by detach(), and firmata::FirmataClass::FirmataClass().
attach() [3/6]
void FirmataParser::attach (uint8_t command, stringCallbackFunction newFunction, void * context = NULL)
Attach a callback function for the STRING_DATA command.
Parameters
command Must be set to STRING_DATA or it will be ignored.
newFunction A reference to the string callback function to attach.
context An optional context to be provided to the callback function (NULL by default).
Note
The context parameter is provided so you can pass a parameter, by reference, to your callback function.
Definition at line 294 of file FirmataParser.cpp.
{
  switch (command) {
    case STRING_DATA:
      currentStringCallback = newFunction;
      currentStringCallbackContext = context;
      break;
  }
}
References firmata::STRING_DATA.
attach() [4/6]
void FirmataParser::attach (uint8_t command, sysexCallbackFunction newFunction, void * context = NULL)
Attach a generic sysex callback function to sysex command.
Parameters
command The ID of the command to attach a callback function to.
newFunction A reference to the sysex callback function to attach.
context An optional context to be provided to the callback function (NULL by default).
Note
The context parameter is provided so you can pass a parameter, by reference, to your callback function.
Definition at line 312 of file FirmataParser.cpp.
{
  (void)command;
  currentSysexCallback = newFunction;
  currentSysexCallbackContext = context;
}
attach() [5/6]
void FirmataParser::attach (uint8_t command, systemCallbackFunction newFunction, void * context = NULL)
Attach a system callback function (supported options are: SYSTEM_RESET, REPORT_VERSION).
Parameters
command The ID of the command to attach a callback function to.
newFunction A reference to the callback function to attach.
context An optional context to be provided to the callback function (NULL by default).
Note
The context parameter is provided so you can pass a parameter, by reference, to your callback function.
Definition at line 272 of file FirmataParser.cpp.
{
  switch (command) {
    case REPORT_VERSION:
      currentReportVersionCallback = newFunction;
      currentReportVersionCallbackContext = context;
      break;
    case SYSTEM_RESET:
      currentSystemResetCallback = newFunction;
      currentSystemResetCallbackContext = context;
      break;
  }
}
References firmata::REPORT_VERSION, and firmata::SYSTEM_RESET.
attach() [6/6]
void FirmataParser::attach (uint8_t command, versionCallbackFunction newFunction, void * context = NULL)
Attach a version callback function (supported option: REPORT_FIRMWARE).
Parameters
command The ID of the command to attach a callback function to.
newFunction A reference to the callback function to attach.
context An optional context to be provided to the callback function (NULL by default).
Note
The context parameter is provided so you can pass a parameter, by reference, to your callback function.
Definition at line 254 of file FirmataParser.cpp.
{
  switch (command) {
    case REPORT_FIRMWARE:
      currentReportFirmwareCallback = newFunction;
      currentReportFirmwareCallbackContext = context;
      break;
  }
}
References firmata::REPORT_FIRMWARE.
detach() [1/2]
void FirmataParser::detach (dataBufferOverflowCallbackFunction)
Detach the buffer overflow callback
Parameters
<unused> Any pointer of type dataBufferOverflowCallbackFunction.
Definition at line 363 of file FirmataParser.cpp.
{
  currentDataBufferOverflowCallback = (dataBufferOverflowCallbackFunction)NULL;
  currentDataBufferOverflowCallbackContext = (void *)NULL;
}
detach() [2/2]
void FirmataParser::detach (uint8_t command)
Detach a callback function for a specified command (such as SYSTEM_RESET, STRING_DATA, ANALOG_MESSAGE, DIGITAL_MESSAGE, etc).
Parameters
command The ID of the command to detatch the callback function from.
Definition at line 337 of file FirmataParser.cpp.
{
  switch (command) {
    case REPORT_FIRMWARE:
      attach(command, (versionCallbackFunction)NULL, NULL);
      break;
    case REPORT_VERSION:
    case SYSTEM_RESET:
      attach(command, (systemCallbackFunction)NULL, NULL);
      break;
    case STRING_DATA:
      attach(command, (stringCallbackFunction)NULL, NULL);
      break;
    case START_SYSEX:
      attach(command, (sysexCallbackFunction)NULL, NULL);
      break;
    default:
      attach(command, (callbackFunction)NULL, NULL);
      break;
  }
}
References attach(), firmata::REPORT_FIRMWARE, firmata::REPORT_VERSION, firmata::START_SYSEX, firmata::STRING_DATA, and firmata::SYSTEM_RESET.
isParsingMessage()
bool FirmataParser::isParsingMessage (void) const
Returns
Returns true if the parser is actively parsing data.
Definition at line 176 of file FirmataParser.cpp.
{
  return (waitForData > 0 || parsingSysex);
}
Referenced by firmata::FirmataClass::isParsingMessage().
parse()
void FirmataParser::parse (uint8_t inputData)
Parse data from the input stream.
Parameters
inputData A single byte to be added to the parser.
Definition at line 81 of file FirmataParser.cpp.
{
  uint8_t command;
  if (parsingSysex) {
    if (inputData == END_SYSEX) {
      //stop sysex byte
      parsingSysex = false;
      //fire off handler function
      processSysexMessage();
    } else {
      //normal data byte - add to buffer
      bufferDataAtPosition(inputData, sysexBytesRead);
      ++sysexBytesRead;
    }
  } else if ((waitForData > 0) && (inputData < 128)) {
    --waitForData;
    bufferDataAtPosition(inputData, waitForData);
    if ((waitForData == 0) && executeMultiByteCommand) { // got the whole message
      switch (executeMultiByteCommand) {
        case ANALOG_MESSAGE:
          if (currentAnalogCallback) {
            (*currentAnalogCallback)(currentAnalogCallbackContext,
                                     multiByteChannel,
                                     (dataBuffer[0] << 7)
                                     + dataBuffer[1]);
          }
          break;
        case DIGITAL_MESSAGE:
          if (currentDigitalCallback) {
            (*currentDigitalCallback)(currentDigitalCallbackContext,
                                      multiByteChannel,
                                      (dataBuffer[0] << 7)
                                      + dataBuffer[1]);
          }
          break;
        case SET_PIN_MODE:
          if (currentPinModeCallback)
            (*currentPinModeCallback)(currentPinModeCallbackContext, dataBuffer[1], dataBuffer[0]);
          break;
        case SET_DIGITAL_PIN_VALUE:
          if (currentPinValueCallback)
            (*currentPinValueCallback)(currentPinValueCallbackContext, dataBuffer[1], dataBuffer[0]);
          break;
        case REPORT_ANALOG:
          if (currentReportAnalogCallback)
            (*currentReportAnalogCallback)(currentReportAnalogCallbackContext, multiByteChannel, dataBuffer[0]);
          break;
        case REPORT_DIGITAL:
          if (currentReportDigitalCallback)
            (*currentReportDigitalCallback)(currentReportDigitalCallbackContext, multiByteChannel, dataBuffer[0]);
          break;
      }
      executeMultiByteCommand = 0;
    }
  } else {
    // remove channel info from command byte if less than 0xF0
    if (inputData < 0xF0) {
      command = inputData & 0xF0;
      multiByteChannel = inputData & 0x0F;
    } else {
      command = inputData;
      // commands in the 0xF* range don't use channel data
    }
    switch (command) {
      case ANALOG_MESSAGE:
      case DIGITAL_MESSAGE:
      case SET_PIN_MODE:
      case SET_DIGITAL_PIN_VALUE:
        waitForData = 2; // two data bytes needed
        executeMultiByteCommand = command;
        break;
      case REPORT_ANALOG:
      case REPORT_DIGITAL:
        waitForData = 1; // one data byte needed
        executeMultiByteCommand = command;
        break;
      case START_SYSEX:
        parsingSysex = true;
        sysexBytesRead = 0;
        break;
      case SYSTEM_RESET:
        systemReset();
        break;
      case REPORT_VERSION:
        if (currentReportVersionCallback)
          (*currentReportVersionCallback)(currentReportVersionCallbackContext);
        break;
    }
  }
}
References firmata::ANALOG_MESSAGE, firmata::DIGITAL_MESSAGE, firmata::END_SYSEX, firmata::REPORT_ANALOG, firmata::REPORT_DIGITAL, firmata::REPORT_VERSION, firmata::SET_DIGITAL_PIN_VALUE, firmata::SET_PIN_MODE, firmata::START_SYSEX, and firmata::SYSTEM_RESET.
Referenced by firmata::FirmataClass::parse(), and firmata::FirmataClass::processInput().
setDataBufferOfSize()
int FirmataParser::setDataBufferOfSize (uint8_t * dataBuffer, size_t dataBufferSize)
Provides a mechanism to either set or update the working buffer of the parser. The method will be enabled when no buffer has been provided, or an overflow condition exists.
Parameters
dataBuffer A pointer to an external buffer used to store parsed data
dataBufferSize The size of the external buffer
Definition at line 189 of file FirmataParser.cpp.
{
    int result;
    if (!allowBufferUpdate) {
      result = __LINE__;
    } else if ((uint8_t *)NULL == dataBuffer) {
      result = __LINE__;
    } else {
      this->dataBuffer = dataBuffer;
      this->dataBufferSize = dataBufferSize;
      allowBufferUpdate = false;
      result = 0;
    }
    return result;
}
The documentation for this class was generated from the following files:
FirmataParser.h
FirmataParser.cpp