firmata::FirmataClass Class Reference
#include <Firmata.h>
Public Types
typedef void(* callbackFunction) (uint8_t, int)
typedef void(* systemCallbackFunction) (void)
typedef void(* stringCallbackFunction) (char *)
typedef void(* sysexCallbackFunction) (uint8_t command, uint8_t argc, uint8_t *argv)
Public Member Functions
FirmataClass ()
void begin ()
void begin (long)
void begin (Stream &s)
void printVersion (void)
void blinkVersion (void)
void printFirmwareVersion (void)
void setFirmwareNameAndVersion (const char *name, byte major, byte minor)
void disableBlinkVersion ()
int available (void)
void processInput (void)
void parse (unsigned char value)
boolean isParsingMessage (void)
void sendAnalog (byte pin, int value)
void sendDigital (byte pin, int value)
void sendDigitalPort (byte portNumber, int portData)
void sendString (const char *string)
void sendString (byte command, const char *string)
void sendSysex (byte command, byte bytec, byte *bytev)
void write (byte c)
void attach (uint8_t command, callbackFunction newFunction)
void attach (uint8_t command, systemCallbackFunction newFunction)
void attach (uint8_t command, stringCallbackFunction newFunction)
void attach (uint8_t command, sysexCallbackFunction newFunction)
void detach (uint8_t command)
byte getPinMode (byte pin)
void setPinMode (byte pin, byte config)
int getPinState (byte pin)
void setPinState (byte pin, int state)
void sendValueAsTwo7bitBytes (int value)
void startSysex (void)
void endSysex (void)
Friends
void FirmataMarshaller::encodeByteStream (size_t bytec, uint8_t *bytev, size_t max_bytes) const
Detailed Description
Definition at line 54 of file Firmata.h.
Member Typedef Documentation
callbackFunction
typedef void(* firmata::FirmataClass::callbackFunction) (uint8_t, int)
Definition at line 57 of file Firmata.h.
stringCallbackFunction
typedef void(* firmata::FirmataClass::stringCallbackFunction) (char *)
Definition at line 59 of file Firmata.h.
sysexCallbackFunction
typedef void(* firmata::FirmataClass::sysexCallbackFunction) (uint8_t command, uint8_t argc, uint8_t *argv)
Definition at line 60 of file Firmata.h.
systemCallbackFunction
typedef void(* firmata::FirmataClass::systemCallbackFunction) (void)
Definition at line 58 of file Firmata.h.
Constructor & Destructor Documentation
FirmataClass()
FirmataClass::FirmataClass ()
The Firmata class. An instance named `Firmata` is created automatically for the user.
Definition at line 80 of file Firmata.cpp.
:
  parser(FirmataParser(parserBuffer, MAX_DATA_BYTES))
{
  firmwareVersionCount = 0;
  firmwareVersionVector = 0;
  blinkVersionDisabled = false;
  // Establish callback translation to parser callbacks
  parser.attach(ANALOG_MESSAGE, (FirmataParser::callbackFunction)staticAnalogCallback, (void *)NULL);
  parser.attach(DIGITAL_MESSAGE, (FirmataParser::callbackFunction)staticDigitalCallback, (void *)NULL);
  parser.attach(REPORT_ANALOG, (FirmataParser::callbackFunction)staticReportAnalogCallback, (void *)NULL);
  parser.attach(REPORT_DIGITAL, (FirmataParser::callbackFunction)staticReportDigitalCallback, (void *)NULL);
  parser.attach(SET_PIN_MODE, (FirmataParser::callbackFunction)staticPinModeCallback, (void *)NULL);
  parser.attach(SET_DIGITAL_PIN_VALUE, (FirmataParser::callbackFunction)staticPinValueCallback, (void *)NULL);
  parser.attach(STRING_DATA, (FirmataParser::stringCallbackFunction)staticStringCallback, (void *)NULL);
  parser.attach(START_SYSEX, (FirmataParser::sysexCallbackFunction)staticSysexCallback, (void *)NULL);
  parser.attach(REPORT_FIRMWARE, (FirmataParser::versionCallbackFunction)staticReportFirmwareCallback, this);
  parser.attach(REPORT_VERSION, (FirmataParser::systemCallbackFunction)staticReportVersionCallback, this);
  parser.attach(SYSTEM_RESET, (FirmataParser::systemCallbackFunction)staticSystemResetCallback, (void *)NULL);
}
References firmata::ANALOG_MESSAGE, firmata::FirmataParser::attach(), firmata::DIGITAL_MESSAGE, firmata::REPORT_ANALOG, firmata::REPORT_DIGITAL, firmata::REPORT_FIRMWARE, firmata::REPORT_VERSION, firmata::SET_DIGITAL_PIN_VALUE, firmata::SET_PIN_MODE, firmata::START_SYSEX, firmata::STRING_DATA, and firmata::SYSTEM_RESET.
Member Function Documentation
attach() [1/4]
void firmata::FirmataClass::attach (uint8_t command, callbackFunction newFunction)
Referenced by detach().
attach() [2/4]
void FirmataClass::attach (uint8_t command, stringCallbackFunction newFunction)
Attach a callback function for the STRING_DATA command.
Parameters
command Must be set to STRING_DATA or it will be ignored.
newFunction A reference to the string callback function to attach.
Definition at line 427 of file Firmata.cpp.
{
  switch (command) {
    case STRING_DATA:
      currentStringCallback = newFunction;
      break;
  }
}
References firmata::STRING_DATA.
attach() [3/4]
void FirmataClass::attach (uint8_t command, sysexCallbackFunction newFunction)
Attach a generic sysex callback function to sysex command.
Parameters
command The ID of the command to attach a callback function to.
newFunction A reference to the sysex callback function to attach.
Definition at line 441 of file Firmata.cpp.
{
  (void)command;
  currentSysexCallback = newFunction;
}
attach() [4/4]
void FirmataClass::attach (uint8_t command, systemCallbackFunction newFunction)
Attach a callback function for the SYSTEM_RESET command.
Parameters
command Must be set to SYSTEM_RESET or it will be ignored.
newFunction A reference to the system reset callback function to attach.
Definition at line 413 of file Firmata.cpp.
{
  switch (command) {
    case SYSTEM_RESET:
      currentSystemResetCallback = newFunction;
      break;
  }
}
References firmata::SYSTEM_RESET.
available()
int FirmataClass::available (void)
A wrapper for Stream::available()
Returns
The number of bytes remaining in the input stream buffer.
Definition at line 244 of file Firmata.cpp.
{
  return FirmataStream->available();
}
begin() [1/3]
void FirmataClass::begin (void)
Initialize the default Serial transport at the default baud of 57600.
Definition at line 109 of file Firmata.cpp.
{
  begin(57600);
}
Referenced by begin().
begin() [2/3]
void FirmataClass::begin (long speed)
Initialize the default Serial transport and override the default baud. Sends the protocol version to the host application followed by the firmware version and name. blinkVersion is also called. To skip the call to blinkVersion, call Firmata.disableBlinkVersion() before calling Firmata.begin(baud).
Parameters
speed The baud to use. 57600 baud is the default value.
Definition at line 121 of file Firmata.cpp.
{
  Serial.begin(speed);
  blinkVersion();
  begin(Serial);
}
References begin(), and blinkVersion().
begin() [3/3]
void FirmataClass::begin (Stream & s)
Reassign the Firmata stream transport.
Parameters
s A reference to the Stream transport object. This can be any type of transport that implements the Stream interface. Some examples include Ethernet, WiFi and other UARTs on the board (Serial1, Serial2, etc).
Definition at line 134 of file Firmata.cpp.
{
  FirmataStream = &s;
  marshaller.begin(s);
  // do not call blinkVersion() here because some hardware such as the
  // Ethernet shield use pin 13
  printVersion(); // send the protocol version
  printFirmwareVersion(); // send the firmware name and version
}
References firmata::FirmataMarshaller::begin(), printFirmwareVersion(), and printVersion().
blinkVersion()
void FirmataClass::blinkVersion (void)
Blink the Firmata protocol version to the onboard LEDs (if the board has an onboard LED). If VERSION_BLINK_PIN is not defined in Boards.h for a particular board, then this method does nothing. The first series of flashes indicates the firmware major version (2 flashes = 2). The second series of flashes indicates the firmware minor version (5 flashes = 5).
Definition at line 159 of file Firmata.cpp.
{
#if defined(VERSION_BLINK_PIN)
  if (blinkVersionDisabled) return;
  // flash the pin with the protocol version
  pinMode(VERSION_BLINK_PIN, OUTPUT);
  strobeBlinkPin(VERSION_BLINK_PIN, FIRMATA_FIRMWARE_MAJOR_VERSION, 40, 210);
  delay(250);
  strobeBlinkPin(VERSION_BLINK_PIN, FIRMATA_FIRMWARE_MINOR_VERSION, 40, 210);
  delay(125);
#endif
}
References FIRMATA_FIRMWARE_MAJOR_VERSION, and FIRMATA_FIRMWARE_MINOR_VERSION.
Referenced by begin().
detach()
void FirmataClass::detach (uint8_t command)
Detach a callback function for a specified command (such as SYSTEM_RESET, STRING_DATA, ANALOG_MESSAGE, DIGITAL_MESSAGE, etc).
Parameters
command The ID of the command to detatch the callback function from.
Definition at line 452 of file Firmata.cpp.
{
  switch (command) {
    case SYSTEM_RESET:
      attach(command, (systemCallbackFunction)NULL);
      break;
    case STRING_DATA:
      attach(command, (stringCallbackFunction)NULL);
      break;
    case START_SYSEX:
      attach(command, (sysexCallbackFunction)NULL);
      break;
    default:
      attach(command, (callbackFunction)NULL);
      break;
  }
}
References attach(), firmata::START_SYSEX, firmata::STRING_DATA, and firmata::SYSTEM_RESET.
disableBlinkVersion()
void FirmataClass::disableBlinkVersion ()
Provides a means to disable the version blink sequence on the onboard LED, trimming startup time by a couple of seconds. Call this before Firmata.begin(). It only applies when using the default Serial transport.
Definition at line 177 of file Firmata.cpp.
{
  blinkVersionDisabled = true;
}
endSysex()
void FirmataClass::endSysex (void)
A helper method to write the end of a Sysex message transmission.
Definition at line 67 of file Firmata.cpp.
{
  FirmataStream->write(END_SYSEX);
}
References firmata::END_SYSEX.
getPinMode()
byte FirmataClass::getPinMode (byte pin)
Parameters
pin The pin to get the configuration of.
Returns
The configuration of the specified pin.
Definition at line 474 of file Firmata.cpp.
{
  return pinConfig[pin];
}
getPinState()
int FirmataClass::getPinState (byte pin)
Parameters
pin The pin to get the state of.
Returns
The state of the specified pin.
Definition at line 498 of file Firmata.cpp.
{
  return pinState[pin];
}
isParsingMessage()
boolean FirmataClass::isParsingMessage (void)
Returns
Returns true if the parser is actively parsing data.
Definition at line 272 of file Firmata.cpp.
{
  return parser.isParsingMessage();
}
References firmata::FirmataParser::isParsingMessage().
parse()
void FirmataClass::parse (unsigned char value)
Parse data from the input stream.
Parameters
inputData A single byte to be added to the parser.
Definition at line 264 of file Firmata.cpp.
{
    parser.parse(inputData);
}
References firmata::FirmataParser::parse().
printFirmwareVersion()
void FirmataClass::printFirmwareVersion (void)
Sends the firmware name and version to the Firmata host application. The major and minor version numbers are the first 2 bytes in the message. The following bytes are the characters of the firmware name.
Definition at line 187 of file Firmata.cpp.
{
  if (firmwareVersionCount) { // make sure that the name has been set before reporting
    marshaller.sendFirmwareVersion(static_cast<uint8_t>(firmwareVersionVector[0]), static_cast<uint8_t>(firmwareVersionVector[1]), (firmwareVersionCount - 2), reinterpret_cast<uint8_t *>(&firmwareVersionVector[2]));
  }
}
References firmata::FirmataMarshaller::sendFirmwareVersion().
Referenced by begin().
printVersion()
void FirmataClass::printVersion (void)
Send the Firmata protocol version to the Firmata host application.
Definition at line 147 of file Firmata.cpp.
{
  marshaller.sendVersion(FIRMATA_PROTOCOL_MAJOR_VERSION, FIRMATA_PROTOCOL_MINOR_VERSION);
}
References FIRMATA_PROTOCOL_MAJOR_VERSION, FIRMATA_PROTOCOL_MINOR_VERSION, and firmata::FirmataMarshaller::sendVersion().
Referenced by begin().
processInput()
void FirmataClass::processInput (void)
Read a single int from the input stream. If the value is not = -1, pass it on to parse(byte)
Definition at line 252 of file Firmata.cpp.
{
  int inputData = FirmataStream->read(); // this is 'int' to handle -1 when no data
  if (inputData != -1) {
    parser.parse(inputData);
  }
}
References firmata::FirmataParser::parse().
sendAnalog()
void FirmataClass::sendAnalog (byte pin, int value)
Send an analog message to the Firmata host application. The range of pins is limited to [0..15] when using the ANALOG_MESSAGE. The maximum value of the ANALOG_MESSAGE is limited to 14 bits (16384). To increase the pin range or value, see the documentation for the EXTENDED_ANALOG message.
Parameters
pin The analog pin to send the value of (limited to pins 0 - 15).
value The value of the analog pin (0 - 1024 for 10-bit analog, 0 - 4096 for 12-bit, etc). The maximum value is 14-bits (16384).
Definition at line 289 of file Firmata.cpp.
{
  marshaller.sendAnalog(pin, value);
}
References firmata::FirmataMarshaller::sendAnalog().
sendDigital()
void FirmataClass::sendDigital (byte pin, int value)
Definition at line 300 of file Firmata.cpp.
{
  (void)pin;
  (void)value;
  /* TODO add single pin digital messages to the protocol, this needs to
   * track the last digital data sent so that it can be sure to change just
   * one bit in the packet. This is complicated by the fact that the
   * numbering of the pins will probably differ on Arduino, Wiring, and
   * other boards.
   */
  // TODO: the digital message should not be sent on the serial port every
  // time sendDigital() is called. Instead, it should add it to an int
  // which will be sent on a schedule. If a pin changes more than once
  // before the digital message is sent on the serial port, it should send a
  // digital message for each change.
  // if(value == 0)
  // sendDigitalPortPair();
}
sendDigitalPort()
void FirmataClass::sendDigitalPort (byte portNumber, int portData)
Send an 8-bit port in a single digital message (protocol v2 and later). Send 14-bits in a single digital message (protocol v1).
Parameters
portNumber The port number to send. Note that this is not the same as a `port` on the physical microcontroller. Ports are defined in order per every 8 pins in ascending order of the Arduino digital pin numbering scheme. Port 0 = pins D0 - D7, port 1 = pins D8 - D15, etc.
portData The value of the port. The value of each pin in the port is represented by a bit.
Definition at line 330 of file Firmata.cpp.
{
  marshaller.sendDigitalPort(portNumber, portData);
}
References firmata::FirmataMarshaller::sendDigitalPort().
sendString() [1/2]
void FirmataClass::sendString (byte command, const char * string)
Send a string to the Firmata host application.
Parameters
command Must be STRING_DATA
string A pointer to the char string
Definition at line 352 of file Firmata.cpp.
{
  if (command == STRING_DATA) {
    marshaller.sendString(string);
  }
}
References firmata::FirmataMarshaller::sendString(), and firmata::STRING_DATA.
sendString() [2/2]
void FirmataClass::sendString (const char * string)
Send a string to the Firmata host application.
Parameters
string A pointer to the char string
Definition at line 363 of file Firmata.cpp.
{
  marshaller.sendString(string);
}
References firmata::FirmataMarshaller::sendString().
sendSysex()
void FirmataClass::sendSysex (byte command, byte bytec, byte * bytev)
Send a sysex message where all values after the command byte are packet as 2 7-bit bytes (this is not always the case so this function is not always used to send sysex messages).
Parameters
command The sysex command byte.
bytec The number of data bytes in the message (excludes start, command and end bytes).
bytev A pointer to the array of data bytes to send in the message.
Definition at line 342 of file Firmata.cpp.
{
  marshaller.sendSysex(command, bytec, bytev);
}
References firmata::FirmataMarshaller::sendSysex().
sendValueAsTwo7bitBytes()
void FirmataClass::sendValueAsTwo7bitBytes (int value)
Split a 16-bit byte into two 7-bit values and write each value.
Parameters
value The 16-bit value to be split and written separately.
Definition at line 51 of file Firmata.cpp.
{
  marshaller.encodeByteStream(sizeof(value), reinterpret_cast<uint8_t *>(&value), sizeof(value));
}
setFirmwareNameAndVersion()
void FirmataClass::setFirmwareNameAndVersion (const char * name, byte major, byte minor)
Sets the name and version of the firmware. This is not the same version as the Firmata protocol (although at times the firmware version and protocol version may be the same number).
Parameters
name A pointer to the name char array
major The major version number
minor The minor version number
Definition at line 201 of file Firmata.cpp.
{
  const char *firmwareName;
  const char *extension;
  // parse out ".cpp" and "applet/" that comes from using __FILE__
  extension = strstr(name, ".cpp");
  firmwareName = strrchr(name, '/');
  if (!firmwareName) {
    // windows
    firmwareName = strrchr(name, '\\');
  }
  if (!firmwareName) {
    // user passed firmware name
    firmwareName = name;
  } else {
    firmwareName ++;
  }
  if (!extension) {
    firmwareVersionCount = strlen(firmwareName) + 2;
  } else {
    firmwareVersionCount = extension - firmwareName + 2;
  }
  // in case anyone calls setFirmwareNameAndVersion more than once
  free(firmwareVersionVector);
  firmwareVersionVector = (byte *) malloc(firmwareVersionCount + 1);
  firmwareVersionVector[firmwareVersionCount] = 0;
  firmwareVersionVector[0] = major;
  firmwareVersionVector[1] = minor;
  strncpy((char *)firmwareVersionVector + 2, firmwareName, firmwareVersionCount - 2);
}
setPinMode()
void FirmataClass::setPinMode (byte pin, byte config)
Set the pin mode/configuration. The pin configuration (or mode) in Firmata represents the current function of the pin. Examples are digital input or output, analog input, pwm, i2c, serial (uart), etc.
Parameters
pin The pin to configure.
config The configuration value for the specified pin.
Definition at line 486 of file Firmata.cpp.
{
  if (pinConfig[pin] == PIN_MODE_IGNORE)
    return;
  pinConfig[pin] = config;
}
References firmata::PIN_MODE_IGNORE.
setPinState()
void FirmataClass::setPinState (byte pin, int state)
Set the pin state. The pin state of an output pin is the pin value. The state of an input pin is 0, unless the pin has it's internal pull up resistor enabled, then the value is 1.
Parameters
pin The pin to set the state of
state Set the state of the specified pin
Definition at line 509 of file Firmata.cpp.
{
  pinState[pin] = state;
}
startSysex()
void FirmataClass::startSysex (void)
A helper method to write the beginning of a Sysex message transmission.
Definition at line 59 of file Firmata.cpp.
{
  FirmataStream->write(START_SYSEX);
}
References firmata::START_SYSEX.
write()
void FirmataClass::write (byte c)
A wrapper for Stream::available(). Write a single byte to the output stream.
Parameters
c The byte to be written.
Definition at line 373 of file Firmata.cpp.
{
  FirmataStream->write(c);
}
Friends And Related Function Documentation
FirmataMarshaller::encodeByteStream
void FirmataMarshaller::encodeByteStream (size_t bytec, uint8_t * bytev, size_t max_bytes) const [friend]
The documentation for this class was generated from the following files:
Firmata.h
Firmata.cpp