WiFiClientStream Class Reference
#include <WiFiClientStream.h>
Public Member Functions
WiFiClientStream (IPAddress server_ip, uint16_t server_port)
virtual bool maintain ()
virtual void stop ()
Protected Member Functions
virtual bool connect_client ()
Protected Attributes
uint32_t _time_connect = 0
Detailed Description
Definition at line 33 of file WiFiClientStream.h.
Constructor & Destructor Documentation
WiFiClientStream()
WiFiClientStream::WiFiClientStream (IPAddress server_ip, uint16_t server_port) [inline]
create a WiFi stream with a TCP client
Definition at line 75 of file WiFiClientStream.h.
: WiFiStream(server_ip, server_port) {}
Member Function Documentation
connect_client()
virtual bool WiFiClientStream::connect_client () [inline], [protected], [virtual]
check if TCP client is connected
Returns
true if connected
Implements WiFiStream.
Definition at line 42 of file WiFiClientStream.h.
  {
    if (_connected)
    {
      if (_client && _client.connected()) return true;
      stop();
    }
    // active TCP connect
    if (WiFi.status() == WL_CONNECTED)
    {
      // if the client is disconnected, try to reconnect every 5 seconds
      if (millis() - _time_connect >= MILLIS_RECONNECT)
      {
        _connected = _client.connect(_remote_ip, _port);
        if (!_connected)
        {
          _time_connect = millis();
        }
        else if (_currentHostConnectionCallback)
        {
          (*_currentHostConnectionCallback)(HOST_CONNECTION_CONNECTED);
        }
      }
    }
    return _connected;
  }
References WiFiStream::_client, WiFiStream::_connected, WiFiStream::_currentHostConnectionCallback, WiFiStream::_port, WiFiStream::_remote_ip, _time_connect, HOST_CONNECTION_CONNECTED, MILLIS_RECONNECT, and stop().
Referenced by maintain().
maintain()
virtual bool WiFiClientStream::maintain () [inline], [virtual]
maintain WiFi and TCP connection
Returns
true if WiFi and TCP connection are established
Implements WiFiStream.
Definition at line 81 of file WiFiClientStream.h.
  {
    return connect_client();
  }
References connect_client().
stop()
virtual void WiFiClientStream::stop () [inline], [virtual]
stop client connection
Implements WiFiStream.
Definition at line 89 of file WiFiClientStream.h.
  {
    if (_client)
    {
      _client.stop();
      if (_currentHostConnectionCallback)
      {
        (*_currentHostConnectionCallback)(HOST_CONNECTION_DISCONNECTED);
      }
    }
    _connected = false;
    _time_connect = millis();
  }
References WiFiStream::_client, WiFiStream::_connected, WiFiStream::_currentHostConnectionCallback, _time_connect, and HOST_CONNECTION_DISCONNECTED.
Referenced by connect_client().
Field Documentation
_time_connect
uint32_t WiFiClientStream::_time_connect = 0 [protected]
Definition at line 36 of file WiFiClientStream.h.
Referenced by connect_client(), and stop().
The documentation for this class was generated from the following file:
WiFiClientStream.h