BLEStream Class Reference
#include <BLEStream.h>
Public Member Functions
BLEStream (unsigned char req=0, unsigned char rdy=0, unsigned char rst=0)
void begin (...)
bool poll ()
void end ()
void setFlushInterval (int)
virtual int available (void)
virtual int peek (void)
virtual int read (void)
virtual void flush (void)
virtual size_t write (uint8_t byte)
virtual operator bool ()
Detailed Description
Definition at line 27 of file BLEStream.h.
Constructor & Destructor Documentation
BLEStream()
BLEStream::BLEStream (unsigned char req = 0, unsigned char rdy = 0, unsigned char rst = 0)
Definition at line 78 of file BLEStream.h.
                                                                            :
#if defined(_VARIANT_ARDUINO_101_X_)
  BLEPeripheral()
#else
  BLEPeripheral(req, rdy, rst)
#endif
{
  this->_txCount = 0;
  this->_rxHead = this->_rxTail = 0;
  this->_flushed = 0;
  this->_flushInterval = BLESTREAM_TXBUFFER_FLUSH_INTERVAL;
  BLEStream::_instance = this;
  addAttribute(this->_uartService);
  addAttribute(this->_uartNameDescriptor);
  setAdvertisedServiceUuid(this->_uartService.uuid());
  addAttribute(this->_rxCharacteristic);
  addAttribute(this->_rxNameDescriptor);
  this->_rxCharacteristic.setEventHandler(BLEWritten, BLEStream::_received);
  addAttribute(this->_txCharacteristic);
  addAttribute(this->_txNameDescriptor);
}
References BLESTREAM_TXBUFFER_FLUSH_INTERVAL.
Member Function Documentation
available()
int BLEStream::available (void) [virtual]
Definition at line 127 of file BLEStream.h.
{
// BLEPeripheral::poll only calls delay(1) in CurieBLE so skipping it here to avoid the delay
#ifndef _VARIANT_ARDUINO_101_X_
  // TODO Need to do more testing to determine if all of these calls to BLEPeripheral::poll are
  // actually necessary. Seems to run fine without them, but only minimal testing so far.
  BLEPeripheral::poll();
#endif
  int retval = (this->_rxHead - this->_rxTail + sizeof(this->_rxBuffer)) % sizeof(this->_rxBuffer);
#ifdef BLE_SERIAL_DEBUG
  if (retval > 0) {
    Serial.print(F("BLEStream::available() = "));
    Serial.println(retval);
  }
#endif
  return retval;
}
begin()
void BLEStream::begin (...)
Definition at line 101 of file BLEStream.h.
{
  BLEPeripheral::begin();
#ifdef BLE_SERIAL_DEBUG
  Serial.println(F("BLEStream::begin()"));
#endif
}
end()
void BLEStream::end (void)
Definition at line 119 of file BLEStream.h.
{
  this->_rxCharacteristic.setEventHandler(BLEWritten, (void(*)(BLECentral&, BLECharacteristic&))NULL);
  this->_rxHead = this->_rxTail = 0;
  flush();
  BLEPeripheral::disconnect();
}
References flush().
flush()
void BLEStream::flush (void) [virtual]
Definition at line 174 of file BLEStream.h.
{
  if (this->_txCount == 0) return;
#ifndef _VARIANT_ARDUINO_101_X_
  // ensure there are available packets before sending
  while(!this->_txCharacteristic.canNotify()) {
    BLEPeripheral::poll();
  }
#endif
  this->_txCharacteristic.setValue(this->_txBuffer, this->_txCount);
  this->_flushed = millis();
  this->_txCount = 0;
#ifdef BLE_SERIAL_DEBUG
  Serial.println(F("BLEStream::flush()"));
#endif
}
Referenced by end(), poll(), and write().
operator bool()
BLEStream::operator bool () [virtual]
Definition at line 207 of file BLEStream.h.
{
  bool retval = this->_connected = BLEPeripheral::connected();
#ifdef BLE_SERIAL_DEBUG
  Serial.print(F("BLEStream::operator bool() = "));
  Serial.println(retval);
#endif
  return retval;
}
peek()
int BLEStream::peek (void) [virtual]
Definition at line 145 of file BLEStream.h.
{
#ifndef _VARIANT_ARDUINO_101_X_
  BLEPeripheral::poll();
#endif
  if (this->_rxTail == this->_rxHead) return -1;
  uint8_t byte = this->_rxBuffer[this->_rxTail];
#ifdef BLE_SERIAL_DEBUG
  Serial.print(F("BLEStream::peek() = 0x"));
  Serial.println(byte, HEX);
#endif
  return byte;
}
poll()
bool BLEStream::poll ()
Definition at line 109 of file BLEStream.h.
{
  // BLEPeripheral::poll is called each time connected() is called
  this->_connected = BLEPeripheral::connected();
  if (millis() > this->_flushed + this->_flushInterval) {
    flush();
  }
  return this->_connected;
}
References flush().
read()
int BLEStream::read (void) [virtual]
Definition at line 159 of file BLEStream.h.
{
#ifndef _VARIANT_ARDUINO_101_X_
  BLEPeripheral::poll();
#endif
  if (this->_rxTail == this->_rxHead) return -1;
  this->_rxTail = (this->_rxTail + 1) % sizeof(this->_rxBuffer);
  uint8_t byte = this->_rxBuffer[this->_rxTail];
#ifdef BLE_SERIAL_DEBUG
  Serial.print(F("BLEStream::read() = 0x"));
  Serial.println(byte, HEX);
#endif
  return byte;
}
setFlushInterval()
void BLEStream::setFlushInterval (int interval)
Definition at line 217 of file BLEStream.h.
{
  if (interval > BLESTREAM_MIN_FLUSH_INTERVAL) {
    this->_flushInterval = interval;
  }
}
References BLESTREAM_MIN_FLUSH_INTERVAL.
write()
size_t BLEStream::write (uint8_t byte) [virtual]
Definition at line 191 of file BLEStream.h.
{
#ifndef _VARIANT_ARDUINO_101_X_
  BLEPeripheral::poll();
#endif
  if (this->_txCharacteristic.subscribed() == false) return 0;
  this->_txBuffer[this->_txCount++] = byte;
  if (this->_txCount == sizeof(this->_txBuffer)) flush();
#ifdef BLE_SERIAL_DEBUG
  Serial.print(F("BLEStream::write(0x"));
  Serial.print(byte, HEX);
  Serial.println(F(") = 1"));
#endif
  return 1;
}
References flush().
The documentation for this class was generated from the following file:
BLEStream.h